valsketch/valsketch/views/views.py
from flask import (Blueprint, render_template, redirect, flash, request, url_for, current_app)
from valsketch.forms import SigninForm, SignupForm
from valsketch.models import User, db, Annotation
from  valsketch.helper import file_list, part_list
import numpy.random as random
import os
import json
from jinja2 import Markup
import randomcolor
from flask_login import login_required, logout_user, login_user, current_user


views = Blueprint('views', __name__, url_prefix='')
rand_color = randomcolor.RandomColor();


@views.route('/')
def index():
    return render_template('index.html', active='index');

@views.route('/signin', methods=['GET', 'POST'])
def signin():
    form=SigninForm()
    if form.validate_on_submit():
        user = form.user
        login_user(user)
        return redirect(url_for('views.dashboard'))
    return render_template('signin.html', form=form, active='signin');

@views.route('/dashboard')
def dashboard():
    return render_template('dashboard.html', active='dashboard')

@views.route('/signup', methods=['GET', 'POST'])
def signup():
    form = SignupForm()
    if form.validate_on_submit():
        user = form.user
        user.last_idx = getIdx()
        db.session.add(user)
        db.session.commit()
        flash('Thanks for registering')
        return redirect(url_for('views.signin'))
    return render_template('signup.html', active='signup', form=form);

@views.route('/tool', methods=['GET', 'POST'])
@login_required
def tool():
    if current_user.annotations.count() >= current_user.annotation_limit:
        redirect(url_for('views.logout'))
    if request.method == 'POST':
        annotation = process_request(request.form)
        current_user.last_idx = current_user.last_idx + 1
        db.session.add(annotation)
        db.session.commit()
    sketch_file = file_list[int(current_user.last_idx)];
    sketch_meta, colors = get_sketch_meta(sketch_file)
    return render_template('tool.html', sketch_meta=sketch_meta, colors=colors, sketch_file=sketch_file)

@views.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('views.index'))


def get_sketch_meta(fname):
    fname = fname.strip();
    cat_name = os.path.dirname(fname)
    with open(os.path.join(current_app.root_path, 'static/sketches_svg', fname)) as sketch_file:
        svg = sketch_file.read();
        colors = rand_color.generate(count = len(part_list[cat_name]))

    return ({'parts' : part_list[cat_name],
            'svg'   : Markup(svg),
            'category': cat_name.capitalize()}, colors)

def process_request(user_response):
    annotation = Annotation(
            user_response['sketch_file'],
            user_response['sketch_category'],
            current_user.id,
            user_response['svg_part_paths'],
            user_response['part_paths'])
    return annotation

def getIdx():
    idx_file = os.path.join(current_app.root_path, 'static/idx.txt')
    with open(idx_file, 'r') as f:
        lidx = int(f.read())

    with(open(idx_file, 'w')) as f:
        f.write(str(lidx + 30))

    return lidx





# fb client id: 853753161392782
# fb client secret: 72d8b0c67dacfe2f2fc415c3137758e1


#@app.route('/')
#def index():
#    return render_template('index.html', active='index');
    #if not google.authorized:
    #    return redirect(url_for("google.login"))
    #resp = google.get("plus/v1/people/me")
    #assert resp.ok, resp.text
    #return "You are {email} on Google".format(email=resp.json()["emails"][0]["value"])

#app.secret_key = "supersekrit"
#blueprint = make_google_blueprint(
#    client_id="1096611460311-1fv15mis6p6sl6utj4pc5tcgl120hhup.apps.googleusercontent.com",
#    client_secret="sRixDroNfhH9RWPNk4gYjhMu",
#    scope=["profile", "email"]
#)
#app.register_blueprint(blueprint, url_prefix="/login")

valsketch/valsketch/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Sketch Annotator | VAL</title>

    {% block head %}
    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- jquery UI -->
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/ui-darkness/jquery-ui.css">

    <!-- font-awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">

    <!-- fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{{ url_for('static', filename='css/ie10-viewport-bug-workaround.css') }}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{{ url_for('static', filename='js/ie-emulation-modes-warning.js') }}" ></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% endblock %}
  </head>

  <body>

    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Video Analytics Lab | SAv0.1</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
              {% if current_user.is_authenticated %}
                {% if current_user.annotations.count() >= current_user.annotation_limit %}
                <li class="bg-danger"><a href="{{ url_for('views.dashboard') }}">LIMIT EXCEEDED!</a></li>
                {% endif %}
            {% endif %}
              <li {% if active == "index" %} class="active" {% endif %}><a href="{{ url_for('views.index') }}">Home</a></li>
              {% if current_user.is_authenticated %}
                  <li {% if active == "dashboard" %} class="active" {% endif %}><a href="{{ url_for('views.dashboard') }}">{{ current_user.username }}</a></li>
                  <li {% if active == "tool" %} class="active" {% endif %}><a href="{% if current_user.annotations.count() >= current_user.annotation_limit %}
                          {{ url_for('views.dashboard') }}
                      {% else %}
                         {{ url_for('views.tool') }}
                      {% endif %}">Tool</a></li>
                  <li><a href="{{ url_for('views.logout') }}">Logout</a></li>
              {% else %}
                  <li {% if active == "signin" %} class="active" {% endif %}><a href="{{ url_for('views.signin') }}">Sign In</a></li>
                  <li {% if active == "signup" %} class="active" {% endif %}><a href="{{ url_for('views.signup') }}">Sign Up</a></li>
              {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>


    {% block content %}
    {% endblock %}


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{{ url_for('static', filename='js/jquery.min.js') }}"><\/script>')</script>

    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>

    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{{ url_for('static', filename='js/ie10-viewport-bug-workaround.js') }}"></script>
    {% block script %}
    {% endblock %}
  </body>
</html>

valsketch/valsketch/templates/dashboard.html
{% extends "base.html" %}

  {% block content %}

    <div class="container">

        <div class="row">
            <div class="col-sm-12">
                <h2> User Information </h1>
                <h3> Email </h3>
                {{ current_user.email }}
                <h3> Username </h3>
                {{ current_user.username }}
                <h3> Task Status </h3>
                You have annotated <b>{{ current_user.annotations.count() }}</b> of <b>{{ current_user.annotation_limit }}</b> sketches.

                {% if current_user.annotations.count() >= current_user.annotation_limit %}
                <h3 class="bg-danger">Hey. You have exceeded your annotation quota. Please create another account
                    with a different username and password to continue. (Psst: we recommend appending a number to your previous
                    account details)
                </h3>
                {% endif %}

            </div>
        </div>
    </div> <!-- /container -->
  {% endblock content %}

valsketch/valsketch/templates/index.html
{% extends "base.html" %}

    {% block content %}
    <div class="container">
        <div class="row">
        <div class="col-xs-12 text-center">
          <h1 class="cover-heading">Sketch Annotator v0.1</h1>
          <p class="lead">Help us improve our Sketch Annotation Tool</p>
          <p class="lead">
          <a href="{{ url_for('views.signin') }}" class="btn btn-lg btn-default">Get Started</a>
          </p>
        </div>
        </div>
    </div> <!-- /container -->
    {% endblock content %}

valsketch/valsketch/templates/signin.html
{% extends "base.html" %}


      {% block content %}

    <div class="container">
    <form action="{{ url_for('views.signin') }}" class="form-signin" method="POST">
            <div style="display: none">
            {{ form.csrf_token }}
            </div>
            <h2 class="form-signin-heading">Please Sign In</h2>

            <div class="form-group {% if form.email.errors %} has-error {% endif %}">
            {{ form.email.label(class="sr-only")  }}
            {{ form.email(placeholder="Enter email address", class="form-control") }} 
            <p class="help-block">
            {{ form.email.errors[0] }} 
            </div>

            <div class="form-group {% if form.password.errors %} has-error {% endif %}">
            {{ form.password.label(class="sr-only") }}
            {{ form.password(placeholder="Enter Password", class="form-control") }}
            <p class="help-block">
            {{ form.password.errors[0] }}
            </div>


            {{ form.recaptcha }}
            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign In</button>
    </form>

    </div> <!-- /container -->
  {% endblock content %}

valsketch/valsketch/templates/signup.html
{% extends "base.html" %}


  {% block content %}
    <div class="container">

    <form action="{{ url_for('views.signup') }}" class="form-signin" method="POST">
            <div style="display: none">
            {{ form.csrf_token }}
            </div>
            <h2 class="form-signin-heading">Please sign up</h2>

            <div class="form-group {% if form.username.errors %} has-error {% endif %}">
            {{ form.username.label(class="sr-only") }}
            {{form.username(placeholder="Username", class="form-control")}}
            <p class="help-block">
            {{ form.username.errors[0] }}
            
            </div>

            <div class="form-group {% if form.password.errors %} has-error {% endif %}">
            {{ form.password.label(class="sr-only") }}
            {{ form.password(placeholder="Enter Password", class="form-control") }}
            <p class="help-block">
            {{ form.password.errors[0] }}
            </div>
            <div class="form-group {% if form.confirm.errors %} has-error {% endif %}">
            {{ form.confirm.label(class="sr-only") }}
            {{ form.confirm(placeholder="Reenter password", class="form-control") }}
            <p class="help-block">
            {{ form.confirm.errors[0] }}
            </div>

            <div class="form-group {% if form.email.errors %} has-error {% endif %}">
            {{ form.email.label(class="sr-only")  }}
            {{ form.email(placeholder="Enter email address", class="form-control") }} 
            <p class="help-block">
            {{ form.email.errors[0] }} 
            </div>

            {{ form.recaptcha }}
            <div class="form-group {% if form.accept_tos.errors %} has-error {% endif %}">
            <label class="checkbox">
            {{form.accept_tos}} 
            {{form.accept_tos.label}}
            </label>
            <p class="help-block">
            {{ form.accept_tos.errors[0] }}
            
            </div>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign Up</button>
    </form>


    </div> <!-- /container -->
  {% endblock content %}

valsketch/valsketch/templates/tool.html
{% extends "base.html" %}

{% block content %}

<style type="text/css" media="all">
  {% for part_name in sketch_meta['parts'] %}
  #add-{{ part_name }}:hover, #remove-{{ part_name }}:hover {
    background-color: {{ colors[loop.index0] }};
  }
  {% endfor %}
</style>

<div class="container-fluid">
    <div class="row">
      <div class="col-sm-3">
        <div class="row">
          <div id="control-list" class="col-sm-12">
            <h3>Tools</h3>
            <div class="btn-group-vertical" role="group">
              <button type="button" class="btn btn-md btn-default" id="draw-button" disabled="disabled">
                <span class="fa fa-pencil" aria-hidden="true"></span> Draw
              </button>
              <button type="button" class="btn btn-md btn-default" id="delete-button" disabled="disabled">
                <span class="fa fa-trash-o" aria-hidden="true"></span> Delete
              </button>
              <button type="button" class="btn btn-md btn-default" id="complete-button" disabled="disabled">
                <span class="fa fa-dot-circle-o" aria-hidden="true"></span> Complete
              </button>
              <button type="button" class="btn btn-md btn-default" id="undo-button" disabled="disabled">
                <span class="fa fa-undo" aria-hidden="true"></span> Undo
              </button>
            </div>
          </div>
        </div>
        <div class="row">
        <div id="part-list" class="col-sm-12">
          <h3>Parts of {{ sketch_meta['category'] }}</h3>
            {% for part_name in sketch_meta['parts'] %}
            <div class="row part-container" id="{{ part_name}}-container">
                <div id="{{ part_name }}-status"
                    class="part-status col-sm-2">0</div>
                <div class="part-name col-sm-6">
                  <div class="color-indicator" style="background-color: {{ colors[loop.index0] }}; border: 1px solid {{ colors[loop.index0] }}"></div>
                  {{ part_name }}
                </div>
                <div class="part-add col-sm-2" id="add-{{ part_name }}">+</div>
                <div class="part-remove col-sm-2" id="remove-{{ part_name }}">-</div>
                <span class="part-color" id="{{ colors[loop.index0] }}"></span>
            </div>
            {% endfor %}
        </div>
      </div>

      <div class="row">
        <div class="col-sm-12">
          <form action="{{ url_for('views.tool') }}" id="form-done" method="POST">
            <button class="btn btn-lg btn-success btn-block" type="submit">Done</button>
            <input type="hidden" value="{{ sketch_file }}" name="sketch_file" />
            <input type="hidden" value="{{ sketch_meta['category'] }}" name="sketch_category" />
          </form>
        </div>
      </div>
        </div>
        
        <div class="col-sm-8 col-sm-offset-1">
          <canvas id="myCanvas" width="800" height="800" style="border: solid 2px black">
        </canvas>
        </div>

  </div>

    <div style="display: none">
    {{ sketch_meta['svg'] }}
    </div>
</div>


{% endblock %}

{% block script %}
    <script src="{{ url_for('static', filename='js/paper-full.js') }}"></script>
    <script type="text/javascript" charset="utf-8">
    /* install paper */
     paper.install(window); 
    </script>
    <script src="{{ url_for('static', filename='js/tool.js') }}"></script>
    <script src="{{ url_for('static', filename='js/draw.js') }}"></script>
    <script src="{{ url_for('static', filename='js/data_submit.js') }}"></script>
{% endblock %}